# left image LDC LUT definition
left_lut_file_path:                 $(find zed_capture)/config/SN5867575_HD_LUT_left.bin

# right image LDC LUT definition
right_lut_file_path:                $(find zed_capture)/config/SN5867575_HD_LUT_right.bin

# location of DL model
dl_model_path:                      $(env TI_DATA_PATH)/tidl_semseg_model/tvmdlr_deeplabv3lite_mobilenetv2_tv_768x432_qat-p2_onnx

# input_format
# should be 1: YUV422
input_format:                       1

# Maximum number of Semantic Segmentation classes
num_classes:                        20

# SDE type
# 0: Single-layer SDE, 1: Multi-layer SDE
sde_algo_type:                      0

# For multi-layer SDE only
# number of layers (2, 3)
num_layers:                         2

# minimum disparity in pixels
# minimum disparity (0 -> 0 pixels, 1 -> -3 pixels)
disparity_min:                      0

# <disparity in pixels>, maximum disparity in pixels
# maximum disparity (0 -> 63 pixels, 1 -> 127 pixels, 2 -> 191 pixels)
disparity_max:                      1

# disparity threshold
sde_confidence_threshold:           1

# <0 - 255>, left-right consistency check threshold in pixels
threshold_left_right:               3

# <0 or 1>, disable/enable texture based filtering
texture_filter_enable:              0

# <0 - 255>, scaled threshold for texture based filtering
threshold_texture:                  100

# <0 - 127>, Optimization penalty constant for small disparity change
aggregation_penalty_p1:             32

# <0 - 255>, Optimization penalty constant for large disparity change
aggregation_penalty_p2:             192

# <0, 1>, median filter in SDE
median_filter_enable:               1

# camera parameters
# camera poses
camera_pitch:                       0.055

# camera height in mm
camera_height:                      647.7

# baseline in mm
stereo_baseline:                    120.0

# OG map configs
# x dimension of a grid (in mm)
grid_x_size:                        200

# y dimension of a grid (in mm)
grid_y_size:                        200

# min x range to be covered by OG map  (in mm)
min_x_range:                       -14000

# max x range to be covered by OG map
max_x_range:                        14000

# min y range to be covered by OG map
min_y_range:                       -14000

# max y range to be covered by OG map
max_y_range:                        14000

# Pixel count threshold of grid for occupied/non-occupied decision
min_pixel_count_grid:               5

# Pixel count threshold of object for occupied/non-occupied decision
min_pixel_count_object:             15

# Maximum number of objects to be detected
# [1 ~ 128]
max_object_to_detect:               50

# Number of neighboring grids to check for connected component analysis
# 8 or 24
num_neighbor_grid:                  24

# Enabling flag of spatial object merge
# 0: disable
# 1: enable
enable_spatial_obj_merge:           1

# Enabling flag of temporal object merge
# 0: disable
# 1: enable
enable_temporal_obj_merge:          1

# Enabling flag of temporal object smoothing
# 0: disable
# 1: enable
enable_temporal_obj_smoothing:      0

# Method to compute distance between objects
# 0: Distance between centers
# 1: Distance between corners
object_distance_mode:               0

# E-Stop Config
#        |<--- max_estop_width --->|
#        --------------------------- -> max_estop_distance 
#        -                         -
#         -                      -
#          -                    -
#           --------------------     -> min_estop_distance = 0
#                    @               -> camera on the robot
#           |<-min_estop_width->|
#
# eStop range is defined by 4 params.
# If there is object in the eStop range, estop flag is published

# Min distance of estop range should be 0 (uint mm)
min_estop_distance:                 0

# Max distance of estop range should be configured (unit mm)
max_estop_distance:                 3000

# Width of estop range at min_estop_distance (unit mm)
min_estop_width:                    1500

# Width of estop range at max_estop_distance (unit mm)
max_estop_width:                    1500

# Minimum number of consecutive frames without any obstacle in EStop range 
# to set m_eStop = 0
min_free_frame_run:                 3

# Minimum number of consecutive frames with any obstacle in EStop range 
# to set m_eStop = 1
min_obs_frame_run:                  1

# interactive mode
#  0 - disable
#  1 - enable
is_interactive:                     0

# Flag to indicate if the graph should be exported
#  0 - disable
#  1 - enable
exportGraph:                        0

# Real-time logging enable.
#  0 - disable
#  1 - enable
rtLogEnable:                        0

# <1 - 8>, pipeline depth
pipeline_depth:                     4

# Core deployment
# merge node in multi-layer SDE
disp_merge_deploy_core:             TIVX_TARGET_A72_0

# holing filling node in multi-layer SDE
hole_filling_deploy_core:           TIVX_TARGET_A72_0

# point cloud creation node in detection
pc_deploy_core:                     TIVX_TARGET_A72_0

# OG map creation node in detection
og_deploy_core:                     TIVX_TARGET_A72_0

# log level for the app
# 0 - DEBUG: Used to show general debug messages
# 1 - INFO: Used to show run-time processing debug
# 2 - WARN: Used to warning developers of possible issues
# 3 - ERROR: Used for most errors
log_level:                          1
